language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly
services:
  - redis-server
install:
  - |
      git clone https://github.com/redis/hiredis.git \
      && pushd hiredis \
      && make \
      && sudo make install \
      && popd
  - |
      git clone https://github.com/nrk/phpiredis.git \
      && pushd phpiredis \
      && phpize \
      && ./configure --enable-phpiredis \
      && make \
      && make install \
      && popd
  - phpenv config-add phpiredis.ini
  - composer self-update
before_script:
  - composer install
matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true
